apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: live-origin-test
spec:
  replicas: 1
  serviceName: live-origin-test
  selector:
    matchLabels:
      name: live-origin      
  template:
    metadata:
      labels:
        name: live-origin        
    spec:
      containers:
        - name: live-origin
          image: unifiedstreaming/live:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /test/test.isml/state
              port: http
          readinessProbe:
            httpGet:
              path: /test/test.isml/state
              port: http
          startupProbe:
            httpGet:
              path: /test/test.isml/state
              port: http
            failureThreshold: 60
            periodSeconds: 10
          resources: {}
          env:
            - name: USP_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: live-origin-test-license-key
                  key: key
            - name: CHANNEL
              value: test
            - name: PUB_POINT_OPTS             
              value: --archiving=1 --archive_length=3600 --archive_segment_length=1800 --dvr_window_length=30 --restart_on_encoder_reconnect --mpd.min_buffer_time=48/25 --mpd.suggested_presentation_delay=48/25 --hls.minimum_fragment_length=48/25 --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time --hls.client_manifest_version=4 --hls.fmp4 --iss.minimum_fragment_length=48/25 --hds.minimum_fragment_length=48/25
          volumeMounts:
            - name: test
              mountPath: /var/www/live/test/
      volumes:
        - name: test
          azureDisk:
            kind: Managed
            diskURI: /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/MC_usp-live-origin_usp-live-origin-cluster_northeurope/providers/Microsoft.Compute/disks/live-origin-assets
            diskName: live-origin-assets
